### ISSUE TITLE
archlinux-logout is not logging out

### ISSUE THREAD

**Issue by asifakonjee** [arcolinux/arcolinux-hypr#2]
I installed hypr wm in Arch Linux (ALCI Pure) and also archlinux-logout. archlinux-logout is working fine except it does not log out of hypr wm. Is there any solution?

**Comment by arcolinuxz** [comment]
see in the code what Archlinux-logout does in our setup

https://github.com/arcolinux/archlinux-logout/blob/21dc05c8dd0e6dacc7571e170a9913d4681a1ae8/usr/share/archlinux-logout/Functions.py#L201

If they changed to small letters then let us know

**Comment by asifakonjee** [comment]
Thanks. Desktop option Hypr was not present. After the input, it is working like a charm! Thanks.
